name: build_docker

on:
  release:
    types: [created]  # 仅在创建新的发布时触发

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up environment variables
        run: |
          REPOSITORY_NAME_PART=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)
          BUILD_TAG=$(date +'%y%m%d%H%M')
          echo "REPOSITORY_NAME_PART=$REPOSITORY_NAME_PART" >> $GITHUB_ENV
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV

      - name: Print environment variables
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPOSITORY_NAME_PART: $REPOSITORY_NAME_PART"
          echo "BUILD_TAG: $BUILD_TAG"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./Docker
          file: ./Docker/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yunzai_napcat_AIO:${{ github.event.release.tag_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/yunzai_napcat_AIO:latest
